apiVersion: v1
kind: Namespace
metadata:
  name: tenant-3
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: sample-role
  namespace: tenant-3
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list", "create", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: sample-role-binding
  namespace: tenant-3
subjects:
- kind: ServiceAccount
  name: sample-service-account
  namespace: tenant-3
roleRef:
  kind: Role
  name: sample-role
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: sample-service-account
  namespace: tenant-3

