---
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  name: tenant-onboarding-tenant-5
  namespace: argo-workflows
spec:
  templates:
    - name: orchestration-steps
      steps:
        - - name: clone-repository
            template: clone-repository
        - - name: create-tenant-infrastructure
            template: create-tenant-infrastructure
    - name: clone-repository
      inputs:
        parameters:
          - name: TENANT_ID
            value: "tenant-5"
          - name: AWS_REGION
            value: "us-west-2"
          - name: TENANT_MODEL
            value: "siloed"
          - name: REPO_URL
            value: "git@github.com:lusoal/eks-saas-gitops.git"
      container:
        image: "public.ecr.aws/t9v6l2p3/saas-argo-workflows-image:5"
        command: ["/bin/sh","-c"]
        args: ['cp /tmp/id_rsa /root/.ssh/ && chmod 600 /root/.ssh/id_rsa && ./01-tenant-clone-repo.sh {{inputs.parameters.REPO_URL}} && cp -r eks-saas-gitops /mnt/vol'] # Create Tenant infra script
        volumeMounts:
        - name: workdir
          mountPath: /mnt/vol
        - name: ssh-key
          mountPath: /tmp/
        env:
          - name: GIT_SSH_COMMAND
            value: "ssh -i /root/.ssh/id_rsa"
    - name: create-tenant-infrastructure
      inputs:
        parameters:
          - name: TENANT_ID
            value: "tenant-5"
          - name: AWS_REGION
            value: "us-west-2"
          - name: TENANT_MODEL
            value: "siloed"
          - name: REPO_URL
            value: "git@github.com:lusoal/eks-saas-gitops.git"
          - name: BUCKET_NAME
            value: terraform-state-tenants-saas-278129817
      container:
        image: "public.ecr.aws/t9v6l2p3/saas-argo-workflows-image:5"
        command: ["/bin/sh","-c"]
        args: ['sleep 1000000'] # Create Tenant infra script
        volumeMounts:
        - name: workdir
          mountPath: /mnt/vol
  entrypoint: orchestration-steps
  volumeClaimTemplates:                
  - metadata:
      name: workdir
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 1Gi
  # - metadata:
  #     name: ssh-key
  #   spec:
  #     accessModes: [ "ReadWriteOnce" ]
  #     storageClassName: standard
  #     resources:
  #       requests:
  #         storage: 1Gi
  volumes:
  - name: ssh-key
    secret:
      secretName: github-ssh-key # Secret need to be created to run this workflow
      items:
        - key: ssh-privatekey
          path: id_rsa
  serviceAccountName: full-permissions-service-account # SA with IRSA permissions