---
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  name: tenant-onboarding-__TENANT_ID__
  namespace: argo-workflows
spec:
  templates:
    - name: orchestration-steps
      steps:
        - - name: clone-repository
            template: clone-repository
        - - name: create-tenant-infrastructure
            template: create-tenant-infrastructure
        - - name: create-tenant-helm-release
            template: create-tenant-helm-release
    - name: clone-repository
      inputs:
        parameters:
          - name: TENANT_ID
            value: "__TENANT_ID__"
          - name: AWS_REGION
            value: "__AWS_REGION__"
          - name: TENANT_MODEL
            value: "__TENANT_MODEL__"
          - name: REPO_URL
            value: "__REPO_URL__"
      container:
        image: "public.ecr.aws/t9v6l2p3/saas-argo-workflows-image:9"
        command: ["/bin/sh","-c"]
        args: ['cp /tmp/id_rsa /root/.ssh/ && chmod 600 /root/.ssh/id_rsa && ./01-tenant-clone-repo.sh {{inputs.parameters.REPO_URL}} && cp -r eks-saas-gitops /mnt/vol'] # Create Tenant infra script
        volumeMounts:
        - name: workdir
          mountPath: /mnt/vol
        - name: ssh-key
          mountPath: /tmp/
        env:
          - name: GIT_SSH_COMMAND
            value: "ssh -i /root/.ssh/id_rsa"
    - name: create-tenant-infrastructure
      inputs:
        parameters:
          - name: TENANT_ID
            value: "__TENANT_ID__"
          - name: AWS_REGION
            value: "__AWS_REGION__"
          - name: BUCKET_NAME
            value: "__BUCKET_NAME__"
      container:
        image: "public.ecr.aws/t9v6l2p3/saas-argo-workflows-image:9"
        command: ["/bin/sh","-c"]
        args: ['./02-tenant-onboarding-infra.sh {{inputs.parameters.AWS_REGION}} {{inputs.parameters.TENANT_ID}} {{inputs.parameters.BUCKET_NAME}}'] # Create Tenant infra script
        volumeMounts:
        - name: workdir
          mountPath: /mnt/vol
    - name: create-tenant-helm-release
      inputs:
        parameters:
          - name: TENANT_ID
            value: "__TENANT_ID__"
          - name: TENANT_MODEL
            value: "__TENANT_MODEL__"
          - name: GIT_USER_EMAIL
            value: "__GIT_USER_EMAIL__"
          - name: GIT_USERNAME
            value: "__GIT_USERNAME__"
      container:
        image: "public.ecr.aws/t9v6l2p3/saas-argo-workflows-image:9"
        command: ["/bin/sh","-c"]
        args: ['cp /tmp/id_rsa /root/.ssh/ && chmod 600 /root/.ssh/id_rsa && ./03-tenant-onboarding.sh {{inputs.parameters.TENANT_ID}} {{inputs.parameters.TENANT_MODEL}} {{inputs.parameters.GIT_USER_EMAIL}} {{inputs.parameters.GIT_USERNAME}}'] # Create Tenant infra script
        volumeMounts:
        - name: workdir
          mountPath: /mnt/vol
        - name: ssh-key
          mountPath: /tmp/
        env:
          - name: GIT_SSH_COMMAND
            value: "ssh -i /root/.ssh/id_rsa"
  entrypoint: orchestration-steps
  volumeClaimTemplates:                
  - metadata:
      name: workdir
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 1Gi
  volumes:
  - name: ssh-key
    secret:
      secretName: github-ssh-key # Secret need to be created to run this workflow
      items:
        - key: ssh-privatekey
          path: id_rsa
  serviceAccountName: full-permissions-service-account # SA with IRSA permissions