apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: tenant-onboarding-
  namespace: argo-workflows
spec:
  serviceAccountName: full-permissions-service-account
  entrypoint: tenant-provisioning
  arguments:
    parameters:
      - name: REPO_URL
        value: "git@github.com:lusoal/eks-saas-gitops.git"
      - name: AWS_REGION
        value: "us-west-2"
      - name: TENANT_ID
        value: "tenant-10"
      - name: TENANT_MODEL
        value: "siloed"
      - name: GIT_USER_EMAIL
        value: "lucasdu@amazon.com"
      - name: GIT_USERNAME
        value: "lusoal"
      - name: GIT_BRANCH
        value: "lucas-branch"
  templates:
    - name: tenant-provisioning
      steps:
        - - name: clone-repository
            templateRef:
              name: tenant-onboarding-template
              template: clone-repository
        - - name: create-tenant-infrastructure
            templateRef:
              name: tenant-onboarding-template
              template: create-tenant-infrastructure
        - - name: create-tenant-helm-release
            templateRef:
              name: tenant-onboarding-template
              template: create-tenant-helm-release
  volumeClaimTemplates:                
  - metadata:
      name: workdir
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 1Gi
  volumes:
  - name: ssh-key
    secret:
      secretName: github-ssh-key # Secret need to be created to run this workflow
      items:
        - key: ssh-privatekey
          path: id_rsa