apiVersion: apps/v1
kind: Deployment
metadata:
  name: netshoot-deployment
  namespace: argo-workflows
spec:
  selector:
    matchLabels:
      app: netshoot
  template:
    metadata:
      labels:
        app: netshoot
    spec:
      serviceAccountName: argo-workflows-server
      containers:
        - name: netshoot-container
          image: nicolaka/netshoot
          command: ["sleep", "infinity"]
