apiVersion: v1
kind: Namespace
metadata:
  name: pooled-tenants
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: pooled-tenants-role
  namespace: pooled-tenants
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list", "create", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: pooled-tenants-role-binding
  namespace: pooled-tenants
subjects:
- kind: ServiceAccount
  name: pooled-tenants
  namespace: pooled-tenants
roleRef:
  kind: Role
  name: pooled-tenants-role
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: pooled-tenants
  namespace: flux-system
spec:
  releaseName: pooled-tenants
  targetNamespace: pooled-tenants
  storageNamespace: pooled-tenants
  interval: 10m0s
  chart:
    spec:
      chart: helm-tenant-chart
      version: 0.1.0
      sourceRef:
        kind: HelmRepository
        name: helm-tenant-chart
  values:
    ingress:
      enabled: false
    tenantId: pooled-tenants
    # Define where to go, based on Karpenter provisioner
    nodeSelector:
      node-type: applications
    tolerations:
      - key: "applications"
        operator: "Exists"
        effect: "NoSchedule"