---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: helm-tenant-chart
  namespace: flux-system
spec:
  type: "oci"
  interval: 1m0s
  url: oci://756050056314.dkr.ecr.us-west-2.amazonaws.com