apiVersion: v1
kind: Namespace
metadata:
  name: tenant-2
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: tenant-2-role
  namespace: tenant-2
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list", "create", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: tenant-2-role-binding
  namespace: tenant-2
subjects:
- kind: ServiceAccount
  name: tenant-2
  namespace: tenant-2
roleRef:
  kind: Role
  name: tenant-2-role
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: tenant-2
  namespace: flux-system
spec:
  releaseName: tenant-2
  targetNamespace: tenant-2
  storageNamespace: tenant-2
  interval: 10m0s
  chart:
    spec:
      chart: helm-tenant-chart
      version: 0.0.1
      sourceRef:
        kind: HelmRepository
        name: helm-tenant-chart
  values:
    # replicaCount: 3 --> not being used
    tenantId: tenant-2
    # If needs to use to interact with Kube API or AWS Service
    serviceAccount:
      create: true
    # Define where to go, based on Karpenter provisioner
    nodeSelector:
      node-type: applications
    tolerations:
      - key: "applications"
        operator: "Exists"
        effect: "NoSchedule"
    apps:
      - name: producer
      - name: consumer
    deployApps: true