apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: tenant-3
  namespace: flux-system
spec:
  releaseName: tenant-3
  targetNamespace: pool-1
  storageNamespace: pool-1
  interval: 10m0s
  chart:
    spec:
      chart: helm-tenant-chart
      version: 0.0.1
      sourceRef:
        kind: HelmRepository
        name: helm-tenant-chart
  values:
    ingress:
      enabled: true
    tenantId: tenant-3
    apps:
      - name: producer
      - name: consumer
    deployApps: false