apiVersion: v1
kind: Namespace
metadata:
  name: karpenter
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: karpenter
  namespace: flux-system
  labels:
    self-managed-add-on: true
    add-on-version: "v0.27.3"
spec:
  releaseName: karpenter
  targetNamespace: karpenter
  storageNamespace: karpenter
  interval: 1m0s
  chart:
    spec:
      chart: karpenter
      version: v0.27.3
      sourceRef:
        kind: HelmRepository
        name: karpenter
  values:
    serviceAccount:
      create: true
      name: karpenter # SA created via eksctl or
      annotations:
        eks.amazonaws.com/role-arn: arn:aws:iam::756050056314:role/karpenter_controller  # Replace
    settings:
      aws:
        clusterName: eks-saas-gitops
        clusterEndpoint: https://2C484BF682A0AD55AD47ACDD7BC5B107.gr7.us-west-2.eks.amazonaws.com  # Replace
        defaultInstanceProfile: KarpenterNodeInstanceProfile-eks-saas-gitops  # Replace
        # interruptionQueueName: eks-upgrade-demo
  install: {}
 