apiVersion: v1
kind: Namespace
metadata:
  name: karpenter
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: karpenter
  namespace: flux-system
  labels:
    add-on-version: "v0.27.3"
spec:
  releaseName: karpenter
  targetNamespace: karpenter
  storageNamespace: karpenter
  interval: 1m0s
  chart:
    spec:
      chart: karpenter
      version: v0.27.3
      sourceRef:
        kind: HelmRepository
        name: karpenter
  values:
    serviceAccount:
      create: true
      name: karpenter # SA created via eksctl or
      annotations:
        eks.amazonaws.com/role-arn: arn:aws:iam::054678736585:role/karpenter_controller
    settings:
      aws:
        clusterName: eks-saas-gitops
        clusterEndpoint: https://E6956EE56A709F39EDD4956EF6C10266.gr7.us-west-2.eks.amazonaws.com
        defaultInstanceProfile: KarpenterNodeInstanceProfile-eks-saas-gitops
        # interruptionQueueName: eks-upgrade-demo
  install: {}
 