apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: karpenter-provisioner
  namespace: flux-system
spec:
  dependsOn:
    - name: infrastructure
  interval: 1m0s
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./gitops/karpenter-provisioner
  prune: true
  validation: client