{{ range .Values.apps }}
{{- if .deploy -}}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .appName }}
  labels:
    app.kubernetes.io/name: "{{$.Chart.Name}}-{{$.Chart.Version }}"
    app.kubernetes.io/instance: "{{ $.Release.Name }}"
    app.kubernetes.io/version: "{{ $.Chart.AppVersion  }}"
    app.kubernetes.io/managed-by: "{{ $.Release.Service }}"
spec:
  type: {{ .service.type }}
  ports:
    - port: {{ .service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: {{ .appName }}
    # app.kubernetes.io/name: "{{$.Chart.Name}}-{{$.Chart.Version }}"
    # app.kubernetes.io/instance: "{{ $.Release.Name }}"
{{ end }}
{{ end }}